### ISSUE TITLE
Evaluating/testing the trained model 

### ISSUE THREAD

**Issue by Atefeh-Yadegarifard** [MDIL-SNU/SEVENNet#4]
Hello. 
I would like to ask how a model that has been trained with SevenNet can be tested/evaluated with the new data that was not used for the training. I specifically want to generate test_result file to see the correlation between the original values and predicted values. 

Also, I uncommented the continue option in input_full.yaml file and set the checkpoint:True to continue from the checkpoint_best.pth file but I encountered an error in the log file stating"unexpected input continue given". How can i solve this issue?

Thank you.

**Comment by YutackPark** [comment]
Hello, sorry for the delayed response,

1. We are currently in the process of introducing the feature you mentioned, the 'test_set' option. For now, you have the option to write your own python code using SEVENNet as package. However, please note that there isn't detailed documentation available for the classes yet. Alternatively, you can use LAMMPS with the desired model and then postprocess on the output.

2. This is my fault. The 'checkpoint' key in the yaml expects file path to the checkpoint you wish yo use for restarting. The correct input would be look like
checkpoint: 'path_to_previous_run/checkpoint_best.pth'
Note that if training continue on the same directory, it will overwrite log and .pt or .pth files. If this is not you want, please backup the previous training directory.

I'll mark this issue as resolved once the 'test_set' feature is updated. Thank you for the feedback.

Thank you.

**Comment by YutackPark** [comment]
We finally updated our main branch with new feature 'sevenn_inference' to obtain correlation between prediction & reference. 

After reinstalltion from main branch, you can get .csv of prediction & reference results by

sevenn_inference {checkpoint} {OUTCARs/POSCARs or .sevenn_data}

Sorry for the delated update. Since I re-wrote tons of code, you need to retrain the potential. You can check README.md for details new features.

Thank you.
