### ISSUE TITLE
[feature suggest] active learning for fine-tuning

### ISSUE THREAD

**Issue by thangckt** [MDIL-SNU/SevenNet#76]
Dear Developers,

I wonder if you have any plan to implement active learning algorithm for fine-tuning?

Thank you so much.

**Comment by YutackPark** [comment]
Nope, we don't have such a plan yet. But we're welcome to have any suggestions. Do you have a particular algorithm in mind?

**Comment by thangckt** [comment]
Dear @YutackPark, 

I do not have my own one.
But I think that some open sources like DPGEN may be a good starting point.

In MACE repo, I also see that they are seemly developing the active learning procedure using ASE md as the exploration engine.

I hope to see such thing with SevenNet too :).
I also really want to contribute if I can do anything.

**Comment by YutackPark** [comment]
I'm happy to hear you're willing to contribute! Feel free to open a pull request for your work, whether it's a draft or a WIP—it’s all welcome. (just conform pre-commit hooks)

I found the part you mentioned about MACE (https://github.com/ACEsuit/mace/blob/575af0171369e2c19e04b115140b9901f83eb00c/mace/cli/active_learning_md.py#L4), and it seems more straightforward than I initially thought.

Since there’s no API, I can help you with the more complicated parts, especially the training. Alternatively, you can wait until the planned refactoring is done, along with the notebook examples. If you have any questions about the code structure or design decisions of SevenNet, feel free to ask—I'll be happy to help.

**Comment by thangckt** [comment]
Hi@YutackPark 

Do you use any messenger? May we have talk about implementing model deviation in 7net?

**Comment by YutackPark** [comment]
Hi @thangckt 
We internally use Teams (recently migrated from Slack), and this is my email: parkyutack@snu.ac.kr
I'm happy to extend SevenNet but if it requires lots of changes or work, I first have to discuss it with my supervisor. (note that our team is almost new to github and its ecosystem.)

If you don't mind, could you send me the suggestions to my email?
